services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES__ADDR: postgres:5432
      POSTGRES__DB: postgres
      POSTGRES__USER: postgres
      POSTGRES__PASSWORD: postgres

  postgres:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "psql -U postgres -d postgres -c 'SELECT 1'"
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  jaeger:
    image: jaegertracing/all-in-one:1.61.0
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"
      - "4318:4318"
