services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES__ADDR: postgres:5432
      POSTGRES__DB: postgres
      POSTGRES__USER: postgres
      POSTGRES__PASSWORD: postgres

  postgres:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "psql -U postgres -d postgres -c 'SELECT 1'"
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
