// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockservice

import (
	"context"
	"itspay/internal/entity"
	"itspay/internal/service"
	"sync"
)

// Ensure, that RatesMock does implement service.Rates.
// If this is not the case, regenerate this file with moq.
var _ service.Rates = &RatesMock{}

// RatesMock is a mock implementation of service.Rates.
//
//	func TestSomethingThatUsesRates(t *testing.T) {
//
//		// make and configure a mocked service.Rates
//		mockedRates := &RatesMock{
//			GetRateFunc: func(ctx context.Context) (*entity.Rate, error) {
//				panic("mock out the GetRate method")
//			},
//		}
//
//		// use mockedRates in code that requires service.Rates
//		// and then make assertions.
//
//	}
type RatesMock struct {
	// GetRateFunc mocks the GetRate method.
	GetRateFunc func(ctx context.Context) (*entity.Rate, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetRate holds details about calls to the GetRate method.
		GetRate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGetRate sync.RWMutex
}

// GetRate calls GetRateFunc.
func (mock *RatesMock) GetRate(ctx context.Context) (*entity.Rate, error) {
	if mock.GetRateFunc == nil {
		panic("RatesMock.GetRateFunc: method is nil but Rates.GetRate was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetRate.Lock()
	mock.calls.GetRate = append(mock.calls.GetRate, callInfo)
	mock.lockGetRate.Unlock()
	return mock.GetRateFunc(ctx)
}

// GetRateCalls gets all the calls that were made to GetRate.
// Check the length with:
//
//	len(mockedRates.GetRateCalls())
func (mock *RatesMock) GetRateCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetRate.RLock()
	calls = mock.calls.GetRate
	mock.lockGetRate.RUnlock()
	return calls
}
